// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Purchase struct {
	PurchaseID   int32
	UserID       int32
	ProductID    int32
	StoreName    string
	Amount       string
	Status       string
	PurchaseTime sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
