// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: creditService.proto

package creditService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CreditServiceClient is the client API for CreditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreditServiceClient interface {
	GetCardByUserID(ctx context.Context, in *GetCardByUserIDRequest, opts ...grpc.CallOption) (*GetCardByUserIDResponse, error)
	UpdateCardBalance(ctx context.Context, in *UpdateCardBalanceRequest, opts ...grpc.CallOption) (*UpdateCardBalanceResponse, error)
}

type creditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCreditServiceClient(cc grpc.ClientConnInterface) CreditServiceClient {
	return &creditServiceClient{cc}
}

func (c *creditServiceClient) GetCardByUserID(ctx context.Context, in *GetCardByUserIDRequest, opts ...grpc.CallOption) (*GetCardByUserIDResponse, error) {
	out := new(GetCardByUserIDResponse)
	err := c.cc.Invoke(ctx, "/creditService.CreditService/GetCardByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) UpdateCardBalance(ctx context.Context, in *UpdateCardBalanceRequest, opts ...grpc.CallOption) (*UpdateCardBalanceResponse, error) {
	out := new(UpdateCardBalanceResponse)
	err := c.cc.Invoke(ctx, "/creditService.CreditService/UpdateCardBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreditServiceServer is the server API for CreditService service.
// All implementations must embed UnimplementedCreditServiceServer
// for forward compatibility
type CreditServiceServer interface {
	GetCardByUserID(context.Context, *GetCardByUserIDRequest) (*GetCardByUserIDResponse, error)
	UpdateCardBalance(context.Context, *UpdateCardBalanceRequest) (*UpdateCardBalanceResponse, error)
	mustEmbedUnimplementedCreditServiceServer()
}

// UnimplementedCreditServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCreditServiceServer struct {
}

func (UnimplementedCreditServiceServer) GetCardByUserID(context.Context, *GetCardByUserIDRequest) (*GetCardByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCardByUserID not implemented")
}
func (UnimplementedCreditServiceServer) UpdateCardBalance(context.Context, *UpdateCardBalanceRequest) (*UpdateCardBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCardBalance not implemented")
}
func (UnimplementedCreditServiceServer) mustEmbedUnimplementedCreditServiceServer() {}

// UnsafeCreditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreditServiceServer will
// result in compilation errors.
type UnsafeCreditServiceServer interface {
	mustEmbedUnimplementedCreditServiceServer()
}

func RegisterCreditServiceServer(s grpc.ServiceRegistrar, srv CreditServiceServer) {
	s.RegisterService(&CreditService_ServiceDesc, srv)
}

func _CreditService_GetCardByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetCardByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creditService.CreditService/GetCardByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetCardByUserID(ctx, req.(*GetCardByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_UpdateCardBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).UpdateCardBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creditService.CreditService/UpdateCardBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).UpdateCardBalance(ctx, req.(*UpdateCardBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreditService_ServiceDesc is the grpc.ServiceDesc for CreditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "creditService.CreditService",
	HandlerType: (*CreditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCardByUserID",
			Handler:    _CreditService_GetCardByUserID_Handler,
		},
		{
			MethodName: "UpdateCardBalance",
			Handler:    _CreditService_UpdateCardBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "creditService.proto",
}
